esphome:
  name: curea-battery-monitor
  friendly_name: "Curea Battery Monitor"
  name_add_mac_suffix: true
  # Diese Version wird automatisch per GitHub Actions aktualisiert.
  version: "0.0.0"

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ap:

captive_portal:

one_wire:
  - platform: gpio
    pin: D2
