esphome:
  name: curea-battery-monitor
  friendly_name: "Curea Battery Monitor"
  name_add_mac_suffix: true

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: http_request

wifi:
  ap:

captive_portal:

http_request:

update:
  - platform: http_request
    name: "Firmware Update"
    source: "https://github.com/Arvernus/Curea-Battery-Monitor/releases/latest/download/manifest.json"
    update_interval: 1h

one_wire:
  - platform: gpio
    pin: D2
