name: CI

on:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        file:
          - environment-meter.yml

        esphome-version:
          - stable
          - beta
          - dev
          - latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v6.0.0
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}