name: Build and Release ESPHome Firmware

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.semver.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version using semantic versioning
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          commit_message: "chore: release version %s"

  build:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update ESPHome YAML with new version
        run: |
          FILE="curea-battery-monitor.yaml"
          NEW_VERSION="${{ needs.version.outputs.new_version }}"
          # Falls bereits ein version-Feld existiert, ersetzen wir es. Andernfalls fügen wir es ein.
          if grep -q "^[[:space:]]*version:" "$FILE"; then
            sed -i 's/^\([[:space:]]*version:[[:space:]]*"\)[^"]*\(".*\)/\1'${NEW_VERSION}'\2/' "$FILE"
          else
            sed -i '/^esphome:/a\  version: "'${NEW_VERSION}'"' "$FILE"
          fi
          echo "Updated version in $FILE to ${NEW_VERSION}"

      - name: Build Firmware with ESPHome Build Action
        uses: esphome/build-action@v6
        with:
          configuration: curea-battery-monitor.yaml  # <-- unbedingt angeben
          complete_manifest: true

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ needs.version.outputs.new_version }}"
          release_name: "v${{ needs.version.outputs.new_version }}"
          body: "Automatisch erstelltes Release für Version v${{ needs.version.outputs.new_version }}"
          draft: false
          prerelease: false

      - name: Upload OTA Firmware
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .esphome/build/curea-battery-monitor/curea-battery-monitor.ota.bin
          asset_name: curea-battery-monitor.ota.bin
          asset_content_type: application/octet-stream
